"""Generate every table, figure, and quoted number in the manuscript (D-104).

The paper contains **no hand-typed results**. This module reads the campaign arms, the adversarial
JSON, and the sensitivity analysis, and writes into ``paper/generated/``: booktabs ``tab_*.tex``,
vector ``fig_*.pdf``, and ``numbers.tex`` -- a ``\\newcommand`` for each statistic the prose
quotes. Output is deterministic (fixed seeds/metadata), so ``make paper-artifacts`` twice yields
identical hashes and a reviewer can regenerate exactly what is printed.

By default it **refuses** to build from a dataset whose provenance is not homogeneous (mixed code
versions, dirty tree, a mock run in the live arm ...): such numbers cannot be presented as one
experiment.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import pandas as pd

from acde.analysis import paper_figures as figs
from acde.analysis import paper_stats as ps
from acde.analysis import sensitivity as sens
from acde.analysis import stats
from acde.experiments.configs import ALL_CONFIGS

_DIGITS = ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"]
EFFECT_METRICS = ("mttr_s", "cost_units", "manual_interventions", "decision_correct")
_METRIC_NAME = {
    "mttr_s": "MTTR (s)",
    "cost_units": "cost (units)",
    "manual_interventions": "manual interv.",
    "decision_correct": "decision correct",
    "freshness_s": "freshness (s)",
}


class ProvenanceError(RuntimeError):
    """The merged dataset mixes experimental conditions and must not be presented as one."""


# --- formatting -----------------------------------------------------------------------------------


def tex(text: object) -> str:
    """Escape LaTeX specials in a plain string."""
    out = str(text)
    for ch, rep in (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
    ):
        out = out.replace(ch, rep)
    return out


def true_minus(text: str) -> str:
    """Typeset a leading hyphen-minus as a real minus sign (no line break after it)."""
    return r"\ensuremath{-}" + text[1:] if text.startswith("-") else text


def fnum(x: float | None, sig: int = 3) -> str:
    """Compact fixed-significance number; ``--`` for missing."""
    if x is None or (isinstance(x, float) and x != x):
        return "--"
    if x == 0:
        return "0"
    mag = abs(x)
    if mag >= 1000:
        return true_minus(f"{x:,.0f}".replace(",", "{,}"))
    return true_minus(f"{x:.{max(sig - 1 - int(f'{mag:e}'.split('e')[1]), 0)}f}")


def fp(p: float | None) -> str:
    """P-value: ``<0.001`` below the floor, else 3 decimals."""
    if p is None:
        return "--"
    return "<0.001" if p < 1e-3 else f"{p:.3f}"


def fci(lo: float, hi: float, sig: int = 3) -> str:
    return f"[{fnum(lo, sig)}, {fnum(hi, sig)}]"


def macro_name(*parts: object) -> str:
    """CamelCase, letters-only macro name (LaTeX control words cannot hold digits/underscores)."""
    text = "_".join(str(p) for p in parts)
    words = re.split(r"[^A-Za-z0-9]+", text)
    name = "".join(w[:1].upper() + w[1:] for w in words if w)
    return "N" + re.sub(r"\d", lambda m: _DIGITS[int(m.group())], name)


class Numbers:
    """Collects ``\\newcommand{\\N...}{value}`` definitions for the prose."""

    def __init__(self) -> None:
        self.defs: dict[str, str] = {}

    def add(self, value: object, *parts: object) -> None:
        self.defs[macro_name(*parts)] = str(value)

    def render(self) -> str:
        lines = ["% Generated by acde.analysis.paper_artifacts -- do not edit."]
        lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(self.defs.items())]
        return "\n".join(lines) + "\n"


def booktabs(header: Sequence[str], rows: Sequence[Sequence[str]], colspec: str) -> str:
    """A bare ``tabular`` (the manuscript supplies caption/label via ``table``)."""
    body = "\n".join(" & ".join(r) + r" \\" for r in rows)
    return (
        f"\\begin{{tabular}}{{{colspec}}}\n\\toprule\n{' & '.join(header)} \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n"
    )


# --- tables ---------------------------------------------------------------------------------------


def _median_iqr(vals: Sequence[float]) -> str:
    return f"{fnum(stats.median(vals))} [{fnum(stats.iqr(vals))}]" if vals else "--"


def main_table(prim: pd.DataFrame, configs: Sequence[str]) -> str:
    rows = []
    for c in configs:
        arm = "live" if ((prim["config"] == c) & (prim["arm"] == "live")).any() else "none"
        cells = [tex(c), arm, str(len(ps._values(prim, c, "mttr_s")))]
        cells += [
            _median_iqr(ps._values(prim, c, m))
            for m in ("mttr_s", "cost_units", "manual_interventions", "decision_correct")
        ]
        rows.append(cells)
    header = ["config", "LLM", "$n$", "MTTR (s)", "cost", "manual interv.", "decision correct"]
    return booktabs(header, rows, "llrrrrr")


def _delta_cell(r: dict[str, Any]) -> str:
    lo, hi = r["cliffs_delta_ci"]
    point = true_minus(f"{r['cliffs_delta']:.2f}")
    return f"{point} {fci(lo, hi, sig=2)}"


def effects_table(rows: Sequence[dict[str, Any]]) -> str:
    out = []
    for r in rows:
        star = r"$^{*}$" if r.get("significant") else ""
        out.append(
            [
                tex(r["config"]),
                tex(_METRIC_NAME.get(r["metric"], r["metric"])),
                f"{fnum(r['median_diff'])} {fci(*r['median_diff_ci'])}",
                _delta_cell(r),
                fp(r["p_holm"]) + star,
            ]
        )
    return booktabs(
        [
            "config",
            "metric",
            r"$\Delta$ median [95\% CI]",
            r"Cliff's $\delta$ [95\% CI]",
            r"$p_{\mathrm{Holm}}$",
        ],
        out,
        "llrrr",
    )


def live_mock_table(rows: Sequence[dict[str, Any]]) -> str:
    out = [
        [
            tex(_METRIC_NAME.get(r["metric"], r["metric"])),
            fnum(r["median_treat"]),
            fnum(r["median_control"]),
            _delta_cell(r),
            fp(r["p_holm"]),
        ]
        for r in rows
    ]
    return booktabs(
        ["metric", "live", "mock", r"Cliff's $\delta$ [95\% CI]", r"$p_{\mathrm{Holm}}$"],
        out,
        "lrrrr",
    )


def llm_table(acct: pd.DataFrame) -> str:
    rows = []
    for cfg, r in acct.iterrows():
        deg = r["degraded_fraction"]
        rows.append(
            [
                tex(cfg),
                fnum(r["llm_calls"]),
                fnum(r["llm_cache_hits"]),
                fnum(r["llm_degraded"]),
                fnum(r["llm_invalid"]),
                fnum(r["api_tokens"]),
                fnum(r["llm_latency_s"]),
                "--" if pd.isna(deg) else f"{100 * deg:.0f}\\%",
            ]
        )
    return booktabs(
        [
            "config",
            "calls",
            "cache hits",
            "degraded",
            "invalid",
            "API tokens",
            "latency (s)",
            "degraded \\%",
        ],
        rows,
        "lrrrrrrr",
    )


def scenario_table(table: pd.DataFrame) -> str:
    rows = [[tex(c), *[fnum(v) for v in row]] for c, row in table.iterrows()]
    return booktabs(["config", *[tex(s) for s in table.columns]], rows, "l" + "r" * table.shape[1])


def _rate_cell(r: dict[str, Any] | None) -> str:
    if not r:
        return "--"
    lo, hi = r["wilson95"]
    return f"{r['k']}/{r['n']} [{lo:.4f}, {hi:.4f}]"


def adversarial_table(result: dict[str, Any]) -> str:
    rows = [
        [
            tex(name),
            str(c["n"]),
            _rate_cell(c["containment"]),
            _rate_cell(c["over_block"]),
            _rate_cell(c["exact_agreement"]),
            str(c["n_fail_open"]),
        ]
        for name, c in result["categories"].items()
    ]
    o = result["overall"]
    rows.append(
        [
            r"\textbf{overall}",
            str(result["n_cases"]),
            _rate_cell(o["containment"]),
            _rate_cell(o["over_block"]),
            _rate_cell(o["exact_agreement"]),
            str(o["fail_open_total"]),
        ]
    )
    return booktabs(
        [
            "category",
            "cases",
            "containment [Wilson 95\\%]",
            "over-block",
            "oracle agreement",
            "fail-open",
        ],
        rows,
        "lrllll",
    )


def sensitivity_table(report: dict[str, Any]) -> str:
    rows = []
    for cfg, v in report["human_latency"]["per_config"].items():
        cost = report["cost_by_config"].get(cfg, {})
        be = cost.get("break_even_static_units")
        rows.append(
            [
                tex(cfg),
                fnum(v["median_mttr_s"]),
                fnum(v["break_even_human_median_s"]),
                fnum(cost.get("reduction_pct_at_recorded_params")),
                "--" if be is None else fnum(be),
            ]
        )
    return booktabs(
        [
            "config",
            "MTTR (s)",
            "human break-even (s)",
            "cost reduction (\\%)",
            "static break-even",
        ],
        rows,
        "lrrrr",
    )


# --- orchestration --------------------------------------------------------------------------------


def _headline_numbers(
    nums: Numbers,
    prim: pd.DataFrame,
    comps: Sequence[dict[str, Any]],
    lvm: Sequence[dict[str, Any]],
    report: dict[str, Any],
) -> None:
    for cfg in sorted(set(prim["config"])):
        for metric, key in (
            ("mttr_s", "Mttr"),
            ("cost_units", "Cost"),
            ("manual_interventions", "Interv"),
            ("decision_correct", "Decision"),
        ):
            vals = ps._values(prim, cfg, metric)
            if vals:
                nums.add(fnum(stats.median(vals)), key, cfg, "median")
        nums.add(len(ps._values(prim, cfg, "mttr_s")), "n", cfg)
    for r in comps:
        tag = (r["metric"], r["config"])
        nums.add(fnum(r["median_diff"]), "diff", *tag)
        nums.add(true_minus(f"{r['cliffs_delta']:.2f}"), "delta", *tag)
        lo, hi = r["cliffs_delta_ci"]
        nums.add(true_minus(f"{lo:.2f}"), "deltaLo", *tag)
        nums.add(true_minus(f"{hi:.2f}"), "deltaHi", *tag)
        nums.add(fp(r["p_holm"]), "pHolm", *tag)
        if r["relative_change_pct"] is not None:
            nums.add(true_minus(f"{r['relative_change_pct']:.0f}"), "relpct", *tag)
    for r in lvm:
        nums.add(fnum(r["median_treat"]), "LiveVsMock", r["metric"], "live")
        nums.add(fnum(r["median_control"]), "LiveVsMock", r["metric"], "mock")
        if r["median_treat"] > 0 and r["median_control"] > 0:
            ratio = r["median_treat"] / r["median_control"]
            nums.add(f"{ratio:.0f}", "LiveVsMock", r["metric"], "ratio")
    hl = report["human_latency"]
    nums.add(fnum(hl["baseline_median_mttr_s"]), "baselineMttr")
    for cfg, v in hl["per_config"].items():
        nums.add(fnum(v["break_even_human_median_s"]), "breakEvenHuman", cfg)
    for cfg, v in report["cost_by_config"].items():
        nums.add(fnum(v["reduction_pct_at_recorded_params"]), "costReduction", cfg)
        if v["break_even_static_units"] is not None:
            nums.add(fnum(v["break_even_static_units"], 3), "breakEvenStatic", cfg)


def _usage_numbers(nums: Numbers, df: pd.DataFrame, prov: dict[str, Any] | None) -> None:
    """Live-arm LLM usage totals and the per-run budget caps, for the overhead paragraph."""
    live = df[df["arm"] == "live"]

    def group_thousands(n: float) -> str:
        return f"{int(n):,}".replace(",", "{,}")

    for arm, tag in (("live", "runsArmA"), ("static", "runsArmB"), ("mock", "runsArmC")):
        n_runs = df[(df["arm"] == arm) & (df["metric"] == "mttr_s")]["run_id"].nunique()
        nums.add(n_runs, tag)
    tokens = live[live["metric"] == "api_tokens"]["value"]
    calls = live[live["metric"] == "llm_calls"]["value"]
    if len(tokens):
        nums.add(len(tokens), "runsLive")
        nums.add(group_thousands(tokens.sum()), "apiTokensTotal")
        nums.add(group_thousands(tokens.max()), "apiTokensMaxRun")
        nums.add(group_thousands(calls.sum()), "llmCallsTotal")
        nums.add(int(calls.max()), "llmCallsMaxRun")
    budget = (prov or {}).get("llm_budget")
    if budget:
        nums.add(int(budget["max_calls_per_run"]), "budgetCalls")
        nums.add(group_thousands(budget["max_tokens_per_run"]), "budgetTokens")


def build(
    root: Path,
    out_dir: Path,
    adversarial: Path | None = None,
    adversarial_before: Path | None = None,
    *,
    strict: bool = True,
    seed: int = 20260921,
    n_resamples: int = 2000,
) -> dict[str, str]:
    """Write all generated artifacts under ``out_dir``; returns ``{filename: sha256}``."""
    df = ps.load_campaign(root)
    records = ps.load_manifests(root)
    problems = ps.provenance_problems(records)
    if problems and strict:
        raise ProvenanceError("; ".join(problems))
    out_dir.mkdir(parents=True, exist_ok=True)

    prim = ps.primary(df)
    configs = [c for c in ALL_CONFIGS if c in set(prim["config"])]
    comps = ps.compare_to_baseline(df, EFFECT_METRICS, configs, seed=seed, n_resamples=n_resamples)
    lvm = ps.live_vs_mock(df, (*EFFECT_METRICS, "freshness_s"), seed=seed, n_resamples=n_resamples)
    agent_cfgs = [c for c in configs if ((prim["config"] == c) & (prim["arm"] == "live")).any()]
    acct = ps.llm_accounting(df, agent_cfgs)
    scen = ps.per_scenario_medians(prim, "mttr_s", configs)
    prov = next((r["provenance"] for r in records if "provenance" in r), None)
    params = sens.ModelParams.from_provenance(prov) if prov else sens.ModelParams.from_settings()
    report = sens.sensitivity_report(prim, params)

    nums = Numbers()
    nums.add(len(records), "runsTotal")
    nums.add(len(problems), "provenanceProblems")
    nums.add(int(params.human_median_s), "humanMedian")
    nums.add(params.human_sigma, "humanSigma")
    _usage_numbers(nums, df, prov)
    cost_scen = ps.per_scenario_medians(prim, "cost_units", configs)
    for cfg in ("baseline", "full"):
        if cfg in cost_scen.index:
            for scenario, value in cost_scen.loc[cfg].items():
                nums.add(fnum(value), "costScen", cfg, scenario)
    _headline_numbers(nums, prim, comps, lvm, report)

    files: dict[str, str] = {
        "tab_main.tex": main_table(prim, configs),
        "tab_effects.tex": effects_table(comps),
        "tab_live_mock.tex": live_mock_table(lvm),
        "tab_llm.tex": llm_table(acct),
        "tab_scenarios.tex": scenario_table(scen),
        "tab_sensitivity.tex": sensitivity_table(report),
    }
    for tag, path in (("adversarial", adversarial), ("adversarial_before", adversarial_before)):
        if path is not None and path.exists():
            result = json.loads(path.read_text())
            files[f"tab_{tag}.tex"] = adversarial_table(result)
            o = result["overall"]
            nums.add(result["n_cases"], tag, "cases")
            nums.add(o["containment"]["k"], tag, "contained")
            nums.add(o["containment"]["n"], tag, "unsafe")
            nums.add(o["fail_open_total"], tag, "failOpen")
            nums.add(o["gate_errors_total"], tag, "gateErrors")
            nums.add(f"{o['containment']['wilson95'][0]:.4f}", tag, "wilsonLo")
    files["numbers.tex"] = nums.render()
    for name, content in files.items():
        (out_dir / name).write_text(content)

    figs.mttr_distribution(df, configs, out_dir / "fig_mttr.pdf")
    figs.effect_forest(comps, ("mttr_s", "cost_units"), out_dir / "fig_effects.pdf")
    figs.human_sensitivity(
        {c: ps._values(prim, c, "mttr_s") for c in configs if c != "baseline"},
        out_dir / "fig_human_sensitivity.pdf",
        sigma=params.human_sigma,
    )
    if report["cost_sweep_full_vs_baseline"]:
        be = report["cost_by_config"].get("full", {}).get("break_even_static_units")
        figs.cost_sensitivity(report["cost_sweep_full_vs_baseline"], be, out_dir / "fig_cost.pdf")
    figs.scenario_heatmap(scen, out_dir / "fig_scenarios.pdf")
    figs.architecture_diagram(out_dir / "fig_arch.pdf")
    if lvm:
        figs.live_mock_comparison(lvm, out_dir / "fig_live_mock.pdf")

    hashes = {
        p.name: hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(out_dir.iterdir())
        if p.suffix in (".tex", ".pdf")
    }
    (out_dir / "SHA256SUMS").write_text("".join(f"{h}  {n}\n" for n, h in hashes.items()))
    return hashes


def main() -> None:  # pragma: no cover - CLI
    parser = argparse.ArgumentParser(description="Generate paper tables/figures/numbers")
    parser.add_argument("--root", default="results")
    parser.add_argument("--out", default="paper/generated")
    parser.add_argument("--adversarial", default=None)
    parser.add_argument("--adversarial-before", default=None)
    parser.add_argument("--allow-unclean", action="store_true")
    args = parser.parse_args()
    hashes = build(
        Path(args.root),
        Path(args.out),
        Path(args.adversarial) if args.adversarial else None,
        Path(args.adversarial_before) if args.adversarial_before else None,
        strict=not args.allow_unclean,
    )
    print(f"wrote {len(hashes)} artifacts to {args.out}")


if __name__ == "__main__":  # pragma: no cover
    main()
