"""Generate results/results.md from the analysis summary + figures (§6).

Per-metric tables (median, CI, p, Holm p, Cliff's delta), embedded figures, the ablation heatmap, a
comparison of our full-vs-baseline deltas to the paper's 45/25/70 claims, and an appended dump of
DEVIATIONS.md.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from acde.analysis import figures
from acde.analysis.analyze import analyze
from acde.config import get_settings
from acde.logging import get_logger

log = get_logger("analysis.report")

_DEVIATIONS = Path(__file__).resolve().parents[3] / "DEVIATIONS.md"


def _metric_table(summary: dict[str, Any], metric: str) -> str:
    m = summary["by_metric"][metric]
    lines = [
        f"### {metric}",
        "",
        "| config | median | IQR | 95% CI | n |",
        "|---|---|---|---|---|",
    ]
    for config in summary["configs"]:
        c = m["per_config"][config]
        lines.append(
            f"| {config} | {c['median']:.3g} | {c['iqr']:.3g} | "
            f"[{c['ci_lo']:.3g}, {c['ci_hi']:.3g}] | {c['n']} |"
        )
    sig = "yes" if m.get("significant") else "no"
    lines += [
        "",
        f"Paired baseline-vs-full: Wilcoxon p = {m['p_value']:.4g}, "
        f"Holm-adjusted p = {m.get('p_holm', float('nan')):.4g} (significant: {sig}), "
        f"Cliff's delta = {m['cliffs_delta']:.3f} (n_pairs = {m['n_pairs']}).",
        "",
    ]
    return "\n".join(lines)


def _vs_paper_table(summary: dict[str, Any]) -> str:
    settings = get_settings()
    ablation = summary.get("ablation", {}).get("full", {})

    def reduction(metric: str) -> float:
        return -ablation.get(metric, 0.0)  # negative %-change == reduction

    rows = [
        ("MTTR", settings.paper_mttr_pct, reduction("mttr_s")),
        ("Operational cost", settings.paper_cost_pct, reduction("cost_units")),
        (
            "Manual interventions",
            settings.paper_intervention_pct,
            reduction("manual_interventions"),
        ),
    ]
    lines = [
        "## Comparison to the paper's claims",
        "",
        "Reduction = full config vs baseline (positive = improvement).",
        "",
        "| metric | paper claim (reduction) | measured (full vs baseline) |",
        "|---|---|---|",
    ]
    for name, claim, measured in rows:
        lines.append(f"| {name} | ↓{claim:.0f}% | {measured:+.1f}% |")
    caveat = (
        "> Cost uses model v2 (DEVIATIONS D-061): measured compute/storage plus a provisioning "
        "term that credits avoided over-provisioning, so right-sizing configs (autoscale, "
        "optimization, full) reduce cost. Positive = reduction; magnitude depends on the disclosed "
        "provisioning gap."
    )
    lines += ["", caveat, ""]
    return "\n".join(lines)


def build(summary: dict[str, Any], results_dir: Path) -> Path:
    """Render results.md (assumes figures already written under results_dir/figures)."""
    parts = [
        "# ACDE results",
        "",
        "Auto-generated by `acde.analysis.report`. Configs: "
        + ", ".join(summary["configs"])
        + f". Metrics: {', '.join(summary['metrics'])}.",
        "",
        "## Per-metric statistics",
        "",
    ]
    for metric in summary["metrics"]:
        parts.append(_metric_table(summary, metric))

    parts += ["## Figures", ""]
    for name in (
        "mttr_bar.png",
        "cost_bar.png",
        "interventions_bar.png",
        "mttr_cdf.png",
        "ablation_heatmap.png",
    ):
        if (results_dir / "figures" / name).exists():
            parts.append(f"![{name}](figures/{name})")
            parts.append("")

    parts.append(_vs_paper_table(summary))

    parts += ["## Deviations from the paper / spec", ""]
    parts.append(_DEVIATIONS.read_text() if _DEVIATIONS.exists() else "(DEVIATIONS.md not found)")

    out = results_dir / "results.md"
    out.write_text("\n".join(parts) + "\n")
    log.info("report_written", extra={"path": str(out)})
    return out


def build_report(results_dir: Path | None = None) -> Path:
    """Full pipeline: analyze → figures → report."""
    settings = get_settings()
    results_dir = results_dir or Path(settings.results_dir)
    summary = analyze(results_dir)
    figures.build_all(summary, results_dir / "figures")
    return build(summary, results_dir)


def main() -> None:  # pragma: no cover - CLI
    parser = argparse.ArgumentParser(description="ACDE report")
    parser.add_argument("--results-dir", default=None)
    args = parser.parse_args()
    build_report(Path(args.results_dir) if args.results_dir else None)


if __name__ == "__main__":  # pragma: no cover
    main()
